version: '3'
services:
  mockServer:
    image: mockserver/mockserver:mockserver-5.11.1
    # command: -logLevel DEBUG -serverPort 1090 -proxyRemotePort 80 -proxyRemoteHost www.mock-server.com
    command: -logLevel DEBUG -serverPort 1090
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    ports:
      - "1080:1090"
    volumes:
      - ./stubs:/config
